workflows:
  expo-android:
    name: Expo Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_credentials  # Contains EXPO_TOKEN
      vars:
        PACKAGE_NAME: "com.tradeedge"
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install nvm and Node.js 18.x
        script: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 18
          nvm use 18
          node -v
      - name: Install dependencies
        script: |
          npm install
          npm install -g eas-cli
      - name: Build Android APK with EAS
        script: |
          eas build --platform android --profile development --non-interactive
          # Fetch the APK URL from the build output and download it
          BUILD_URL=$(eas build:list --platform android --status finished --limit 1 --json | jq -r '.[0].artifacts.buildUrl')
          curl -o app.apk "$BUILD_URL"
    artifacts:
      - app.apk  # Store the downloaded APK as an artifact
    publishing:
      email:
        recipients:
          - your_email@example.com  # Replace with your email
        notify:
          success: true
          failure: true