workflows:
  expo-android:
    name: Expo Android Build
    max_build_duration: 120
    instance_type: linux_x1  
    environment:
      vars:
        PACKAGE_NAME: "com.tradeedge"
      node: 18.x
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g expo-cli
      - name: Prebuild Android
        script: |
          npx expo prebuild --clean
    artifacts:
      - android/app/build/outputs/**/*.apk