workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      vars:
        PACKAGE_NAME: "com.yourapp.name" # Replace with your app's package name
      node: 18.x
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          yarn install
          yarn global add expo-cli
      - name: Build Android APK
        script: |
          npx expo prebuild --clean
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true