workflows:
  expo-android:
    name: Expo Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_credentials
      vars:
        PACKAGE_NAME: "com.tradeedge"
      node: 18.x
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g expo-cli
      - name: Prebuild Android
        script: |
          npx expo prebuild --clean
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true